name: comcat
channels:
- conda-forge
- defaults
- digitalglobe
- ioos
dependencies:
- appnope=0.1.0=py35_0
- asn1crypto=0.22.0=py35_0
- attrs=17.3.0=py_0
- autopep8=1.3.3=py_0
- beautifulsoup4=4.6.0=py35_0
- blas=1.1=openblas
- bleach=2.0.0=py35_0
- ca-certificates=2017.11.5=0
- cartopy=0.15.1=py35_5
- certifi=2017.11.5=py35_0
- cffi=1.11.2=py35_0
- chardet=3.0.4=py35_0
- click=6.7=py35_0
- click-plugins=1.0.3=py35_0
- cligj=0.4.0=py35_0
- coverage=4.4.2=py35_0
- cryptography=2.1.4=py35_0
- curl=7.55.1=0
- cycler=0.10.0=py35_0
- decorator=4.1.2=py35_0
- entrypoints=0.2.3=py35_1
- et_xmlfile=1.0.1=py35_0
- expat=2.1.0=3
- fiona=1.7.11=py35_0
- freetype=2.6.3=1
- freexl=1.0.4=0
- future=0.16.0=py35_0
- gdal=2.1.3=py35_7
- geos=3.6.2=1
- giflib=5.1.4=0
- h5py=2.7.1=py35_2
- hdf4=4.2.13=0
- hdf5=1.10.1=1
- html5lib=1.0.1=py_0
- icu=58.2=0
- idna=2.6=py35_1
- ipykernel=4.7.0=py35_0
- ipython=6.2.1=py35_0
- ipython_genutils=0.2.0=py35_0
- ipywidgets=7.0.5=py35_0
- jdcal=1.3=py35_0
- jedi=0.10.2=py35_0
- jinja2=2.10=py35_0
- jpeg=9b=2
- json-c=0.12.1=0
- jsonschema=2.6.0=py35_0
- jupyter=1.0.0=py35_0
- jupyter_client=5.1.0=py35_0
- jupyter_console=5.2.0=py35_0
- jupyter_core=4.4.0=py_0
- kealib=1.4.7=4
- krb5=1.14.2=0
- libdap4=3.18.3=2
- libffi=3.2.1=3
- libgfortran=3.0.0=0
- libiconv=1.15=0
- libnetcdf=4.4.1.1=10
- libpng=1.6.28=2
- libpq=9.6.3=0
- libsodium=1.0.15=1
- libspatialite=4.3.0a=18
- libssh2=1.8.0=2
- libtiff=4.0.9=0
- libxml2=2.9.5=2
- libxslt=1.1.32=0
- lxml=4.1.1=py35_0
- markupsafe=1.0=py35_0
- matplotlib=2.0.0rc2=np112py35_2
- mistune=0.8.3=py_0
- munch=2.2.0=py35_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py35_0
- ncurses=5.9=10
- nose=1.3.7=py35_2
- notebook=5.2.2=py35_1
- numpy=1.12.1=py35_blas_openblas_201
- obspy=1.1.0=py35_1
- olefile=0.44=py35_0
- openblas=0.2.20=6
- openjpeg=2.1.2=2
- openpyxl=2.5.0b1=py35_0
- openssl=1.0.2n=0
- owslib=0.15.0=py_0
- pandas=0.21.1=py35_0
- pandoc=2.0.5=0
- pandocfilters=1.4.1=py35_0
- paramiko=2.3.1=py_0
- patsy=0.4.1=py35_0
- pcre=8.39=0
- pexpect=4.3.1=py35_0
- pickleshare=0.7.4=py35_0
- pillow=4.0.0=py35_1
- pip=9.0.1=py35_0
- pluggy=0.6.0=py_0
- proj4=4.9.3=5
- prompt_toolkit=1.0.15=py35_0
- ptyprocess=0.5.2=py35_0
- py=1.5.2=py_0
- pyasn1=0.3.7=py_0
- pycodestyle=2.3.1=py35_0
- pycparser=2.18=py35_0
- pycrypto=2.6.1=py35_1
- pyepsg=0.3.2=py35_0
- pygments=2.2.0=py35_0
- pynacl=1.1.2=py35_0
- pyopenssl=17.4.0=py35_0
- pyparsing=2.2.0=py35_0
- pyproj=1.9.5.1=py35_0
- pyqt=5.6.0=py35_4
- pyshp=1.2.12=py_0
- pysocks=1.6.7=py35_0
- pytest=3.3.1=py35_0
- pytest-cov=2.5.1=py35_0
- pytest-mpl=0.9=py_0
- python=3.5.4=2
- python-dateutil=2.6.1=py35_0
- pytz=2017.3=py_2
- pyzmq=16.0.2=py35_2
- qt=5.6.2=h9e3eb04_4
- qtconsole=4.3.1=py35_0
- readline=6.2=0
- requests=2.18.4=py35_1
- scipy=1.0.0=py35_blas_openblas_201
- seaborn=0.8.1=py35_0
- setuptools=38.2.4=py35_0
- shapely=1.6.3=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.18=py35_1
- six=1.11.0=py35_1
- sqlalchemy=1.1.13=py35_0
- sqlite=3.13.0=1
- statsmodels=0.8.0=py35_0
- terminado=0.8.1=py35_0
- testpath=0.3.1=py35_0
- tk=8.5.19=2
- tornado=4.5.2=py35_0
- traitlets=4.3.2=py35_0
- urllib3=1.22=py35_0
- wcwidth=0.1.7=py35_0
- webencodings=0.5=py35_0
- wheel=0.30.0=py_1
- widgetsnbextension=3.0.8=py35_0
- xerces-c=3.2.0=0
- xlrd=1.1.0=py_2
- xlsxwriter=1.0.2=py_0
- xlwt=1.3.0=py35_0
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- bcrypt=3.1.4=py35h7e31480_0
- pip:
  - et-xmlfile==1.0.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15
  - ./impact-utils.zip


